# Generated by Django 3.2.9 on 2021-11-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211107_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='patient_email',
            field=models.TextField(blank=True, default='--'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='patient_lastName',
            field=models.TextField(blank=True, default='--', null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='patient_name',
            field=models.TextField(blank=True, default='--', null=True),
        ),
    ]
